config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'
  resources :comments do
    resources :comment_updates, only: [:new, :create, :index]
  end
  resources :stores
  resources :users
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/open' => 'comments#open'
  get '/closed' => 'comments#closed'
  get '/position' => 'users#position'
  get '/store_comments' => 'comments#store_comments'
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :store
    belongs_to :guest
    has_many :comment_updates
    accepts_nested_attributes_for :comment_updates
    validates :case_number, uniqueness: true

    scope :complaint, -> { where(comment_type: 'Complaint') }
    scope :compliment, -> { where(comment_type: 'Compliment') }
    scope :inquiry, -> { where(comment_type: 'Inquiry') }
    scope :open, -> { where(status: 'Open') }
    scope :closed, -> { where(status: 'Closed') }
    scope :eight_hundred, -> { where(source: '1-800#') }
    scope :local, -> { where(source: 'Local') }
    scope :voice, -> { where(source: 'VOICE') }

    COMMENT_TYPES = ["Complaint", "Compliment", "Inquiry"]
    SOURCE = ["1-800#", "VOICE", "Local"]
    URGENT = ["General", "Urgent"]
    CONTACT_TYPE = ["Phone", "Email", "Mail", "Voice", "Other"]
    ORDER_POINT = ["DT", "FC", "Mobile", "Kiosk", "Delivery", "Other"]
    STATUS = ["Open", "Closed"]

    def guest_attributes=(guest)
        self.guest = Guest.find_or_create_by(first_name: guest[:first_name])
        self.guest.update(guest)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]
    before_action :require_log_in

    def index
        @comments = Comment.open.order(store_id: :asc, visit_date: :asc)
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @comments }
        end
    end

    def store_comments
        @comments = Comment.find_by(store_id: params[:store])
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @comments }
        end
        binding.pry
    end

    def show
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @comment }
        end
    end

    def open
        @comments = Comment.open.order(store_id: :asc, visit_date: :asc)
    end

    def closed
        @comments = Comment.closed.order("store_id")
    end

    def new
        @comment = Comment.new
        @comment.guest = Guest.new
    end

    def edit
    end

    def create
        @comment = Comment.create(comment_params)
        if @comment.save
            flash.notice = "Comment Successfully Added"
            redirect_to user_path(session[:user_id])
        else
            flash.alert = "Error Creating Comment"
            render :new
        end
    end

    def update
        if @comment = Comment.update(comment_params)
            flash.notice = "Comment Successfully Edited"
            redirect_to user_path(session[:user_id])
        else
            flash.alert = "Error Editing Comment"
            render :edit
        end
    end

    def destroy
    end

    private
    def set_comment
        @comment = Comment.find(params[:id])
    end
    def comment_params
        params.require(:comment).permit(:visit_date, :visit_time, :comment_type, :source, :urgent, :case_number, :first_issue, :first_issue_comment, :second_issue, :second_issue_comment, :third_issue, :third_issue_comment, :contact_type, :visit_type, :employee_named, :status, :guest_id, :store_id,
            guest_attributes: [:first_name, :last_name, :phone, :email])
    end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
    <%= f.fields_for :guest do |guest| %>
        <%= guest.label :first_name, "First Name" %>
            <%= guest.text_field :first_name, required: "true" %>
        <%= guest.label :last_name, "Last Name" %>
            <%= guest.text_field :last_name, required: "true" %><br>
        <%= guest.label :email, "Email Address" %>
            <%= guest.text_field :email %><br>
        <%= guest.label :email, "Phone" %>
            <%= guest.text_field :phone %><br>
    <% end %>
    <%= f.label :store_id, "Restaurant"%>
    <%= f.collection_select(:store_id, Store.all, :id, :store_number) %>
    <%= f.label :visit_date, "Incident Date"%>
    <%= f.date_field :visit_date, required: "true" %>
    <%= f.label :visit_time, "Incident Time"%>
    <%= f.time_field :visit_time, required: "true" %><br>
    <%= f.label :comment_type, "Type of Comment"%>
    <%= f.select :comment_type, Comment::COMMENT_TYPES, required: "true" %>
    <%= f.label :source, "Source of Comment" %>
    <%= f.select :source, Comment::SOURCE, required: "true" %>
    <%= f.label :urgent, "Urgent or General" %>
    <%= f.select :urgent, Comment::URGENT %><br>
    <%= f.label :case_number, "Case Number" %>
    <%= f.text_field :case_number, required: "true" %><br>
    <%= f.label :first_issue, "Customer Issue 1"%>
    <%= f.text_field :first_issue, required: "true" %><br>
    <%= f.label :first_issue_comment, "Details"%><br>
    <%= f.text_area :first_issue_comment, size: "50 x 4", required: "true"%><br>
    <%= f.label :second_issue, "Customer Issue 2"%>
    <%= f.text_field :second_issue %><br>
    <%= f.label :second_issue_comment, "Details"%><br>
    <%= f.text_area :second_issue_comment, size: "50 x 4"%><br>
    <%= f.label :third_issue, "Customer Issue 3"%>
    <%= f.text_field :third_issue %><br>
    <%= f.label :third_issue_comment, "Details"%><br>
    <%= f.text_area :third_issue_comment, size: "50 x 4" %><br>
    <%= f.label :contact_type, "Contact Type"%>
    <%= f.select :contact_type, Comment::CONTACT_TYPE %>
    <%= f.label :visit_type, "Order Point" %>
    <%= f.select :visit_type, Comment::ORDER_POINT %><br>
    <%= f.label :employee_named, "Employee Named"%>
    <%= f.text_field :employee_named %>
    <%= f.label :status, "Status"%>
    <%= f.select :status, Comment::STATUS %><br>
<%= f.submit %>
<% end %>

app/views/comments/_status.html.erb
<% @comments.each do |c| %>
    <p><%= link_to c.store.store_number, store_path(c.store) %> Case Number: <%=link_to c.case_number, comment_path(c) %> Incident Date: <%= c.visit_date.strftime("%m/%d/%Y") %> Time: <%= c.visit_time.strftime("%I:%M %p") %><br>
    Guest: <%= c.guest.first_name + " " + c.guest.last_name %> Main Issue: <%= c.first_issue %> # Updates <%= c.comment_updates.count %> Status is <%= c.status %> <p>
    <% if c.status == "Open" %>
        <button class="button button-light"><%= link_to 'Edit Comment', edit_comment_path(c) %></button>
        <button class="button button-light"><%= link_to 'Update Comment', new_comment_comment_update_path(c) %></button>
    <% end %>
<% end %>

app/views/comments/closed.html.erb
<h1>Closed Comments</h1>
<%= render 'status' %>

app/views/comments/edit.html.erb
<h1>Edit Comment Details</h1>
<%= render 'form' %>

app/views/comments/index.html.erb
<h1>All Comments</h1>
<%= render 'status' %>

app/views/comments/new.html.erb
<% if flash.alert %>
    <div class="alert alert-danger"><%= flash.alert %></div>
<% end %>
<% if flash.notice %>
    <div class="alert alert-success"><%= flash.notice %></div>
<% end %>
<h1>Enter New Comment Details</h1>
<%= render 'form' %>

app/views/comments/open.html.erb
<h1>Open Comments</h1>
<%= render 'status' %>

app/views/comments/show.html.erb
<% if flash.alert %>
    <div class="alert alert-danger"><%= flash.alert %></div>
<% end %>
<% if flash.notice %>
    <div class="alert alert-success"><%= flash.notice %></div>
<% end %>

<h1 class="myComment" data-id="<%= @comment.id %>">Case Number :<%= @comment.case_number %></h1>
<p><%= link_to @comment.store.store_number, store_path(@comment.store) %> Incident Date: <%= @comment.visit_date.strftime("%m/%d/%Y") %> Time: <%= @comment.visit_time.strftime("%I:%M %p") %> Status: <%= @comment.status %> <br>
    Guest: <%= @comment.guest.first_name + " " + @comment.guest.last_name %> Main Issue: <%= @comment.first_issue %> # Updates <%= @comment.comment_updates.count %> <p>
<% if !@comment.comment_updates.empty? %>
    <button class="button button-light comment-updates" >See Updates</button>
<% end %>
    <button class="button button-light add-updates" >Add Update</button>

<%# form will display on click of 'add update' form will add update to current comment and disply to page. satifies requirement 4. %>
<div id="addUpdate">
    <div id="updateForm">
            <%= form_with(model: [ @comment, @comment.comment_updates.build ], local: true) do |form| %>
        <%= form.label :update_date, "Date Updated" %>
            <%= form.date_field :update_date, required: "true" %>
        <%= form.label :update_type, "Contact Type" %>
            <%= form.select :update_type, Comment::CONTACT_TYPE, required: "true" %>
        <%= form.label :employee_name, "Who Contacted" %>
            <%= form.text_field :employee_name, required: "true" %><br>
        <%= form.label :current_update, "Update" %><br>
            <%= form.text_area :current_update, size: "50x5", required: "true" %><br>
        <%= form.label :status, "Close Comment?" %>
        <%= form.radio_button :status , "Closed"%><br>
        <%= form.submit %><button type="reset">Reset</button>
    <% end %>
    </div>
</div>

<%# section will show the comment updates if they are there. satisfies requirement 3. uses comments/comment.js page  %>
<div id="updates">
</div>

<script>
    $(function(){
        $('.add-updates').on('click', function(){
            $('#updateForm').toggle()
        })
    })

  $(function () {
    $('form').submit(function(event) {
        //prevent form from submitting the default way
        event.preventDefault();
        var values = $(this).serialize();
        var comment_number = $('.myComment').attr('data-id')
        var posting = $.post('/comments/' + comment_number + '/comment_updates', values);
        $('#updateForm').hide()

        posting.done(function(data) {
            let theUpdate = new CommentUpdate(data.update_date,data.update_type, data.employee_name, data.current_update, data.status, data.comment.id)
            theUpdate.displayComment()
      });
    });
  });
  </script>