config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'
  resources :comments do
    resources :comment_updates, only: [:new, :create, :index]
  end
  resources :stores
  resources :users
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/open' => 'comments#open'
  get '/closed' => 'comments#closed'
  get '/position' => 'users#position'
  get '/store_comments' => 'comments#store_comments'
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, :last_name, :position, :username, :password, presence: true
    validates :username, :email, uniqueness: true
    has_secure_password

    scope :gms, -> { where(position: 'General Manager') }

    POSITIONS = ["Owner", "Director", "Operations Manager", "Department Head", "Supervisor", "General Manager", "Manager", "Employee"]
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            flash.notice = "User Successfully Added"
            redirect_to user_show_path
        else
            flash.alert = "Error Creating User"
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require('user').permit(:)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            flash.notice = "User Successfully Added"
            redirect_to user_show_path
        else
            flash.alert = "Error Creating User"
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end

    def position
        @users = User.gms
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :position, :email, :password)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<% if flash.alert %>
    <div class="alert alert-danger"><%= flash.alert %></div>
<% end %>
<% if flash.notice %>
    <div class="alert alert-success"><%= flash.notice %></div>
<% end %>

 <%= form_for @user do |f| %>
    <div class="form-group">
        <%= f.label :first_name, "First Name" %>
            <%= f.text_field :first_name, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :last_name, "Last Name" %>
            <%= f.text_field :last_name, class: "form-control", required: "true" %><br>
    </div>
    <div class="form-group">
        <%= f.label :position, "Position" %>
            <%= f.select :position, User::POSITIONS, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :email, "Email Address" %>
            <%= f.text_field :email, class: "form-control", required: "true" %><br>
    </div>
    <div class="form-group">
        <%= f.label :username, "Create a Username" %>
            <%= f.text_field :username, class: "form-control", required: "true" %>
    </div>
    <div class="form-group">
        <%= f.label :password, "Create a password" %>
            <%= f.password_field :password, class: "form-control", required: "true" %><br>
    </div>
        <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/position.html.erb
<h1>General Managers</h1>
<% @users.each do |u| %>
    <p><%= u.first_name + " " + u.last_name %></p>
<% end %>

app/views/users/show.html.erb
<% if flash.alert %>
    <div class="alert alert-danger"><%= flash.alert %></div>
<% end %>
<% if flash.notice %>
    <div class="alert alert-success"><%= flash.notice %></div>
<% end %>
<h1>Hi, <%= @user.first_name %></h1>

<button class="button button-light"><%= link_to 'Add A Comment', new_comment_path %></button>
<button class="button button-light"><%= link_to 'Open Comments', '/open' %></button>
<button class="button button-light"><%= link_to 'Closed Comments', '/closed' %></button>
<button class="button button-light"><%= link_to 'Restaurants', stores_path %></button>
<button class="button button-light"><%= link_to 'Edit My Account', edit_user_path(@user) %></button>
<button class="button button-light"><%= link_to 'See GMs', '/position' %></button>